### ISSUE TITLE
I got to the JAR part, but I have no idea what to do next

### ISSUE THREAD

**Issue by Supergamer5465** [wode490390/BotClient#4]
all that it says is:
18:10:06 [INFO ] Loading configuration...
18:10:08 [INFO ] Starting Minecraft: Bedrock Edition client version 1.14.60 (protocol version 390)
> 

and then there is an empty command prompt

could you give me some commands to use? all that I could find was "version"

**Comment by good777LUCKY** [comment]
You can use `add`, `close`, `stop`, `version` commands

**Comment by pogchamp-bit** [comment]
pogchamp
